server:
  port: 8080
  #url前缀，访问项目时在8080后加/kknq
  context-path:
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    show-sql: true
    url: jdbc:mysql://127.0.0.1:3306/kknq?useUnicode=true&characterEncoding=utf-8
    user: root
    password: 626520
  jpa:
    hibernate:
      #自动创建表
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
  thymeleaf:
    encoding: UTF-8
    mode: HTML5
    content-type: text/html
    cache: false
